(define-key evil-normal-state-map "zj" 'evil-scroll-down)
(define-key evil-normal-state-map "zk" 'evil-scroll-up)
(define-key evil-normal-state-map "zo" 'evil-jump-backward)
(define-key evil-normal-state-map "zi" 'evil-jump-forward)
(define-key evil-normal-state-map "'q" 'evil-save-and-close)
(map! :ne "SPC e" #'execute-extended-command)
(map! :ne "SPC o n" #'treemacs-add-and-display-current-project)
(map! :ne "SPC o m" #'mu4e)
(map! :ne "SPC o l" #'list-processes)
(map! :ne "SPC TAB j" #'+workspace:switch-next)
(map! :ne "SPC TAB k" #'+workspace:switch-previous)
(map! :ne "'w" #'save-buffer)
(map! :ne "'q" #'+workspace/close-window-or-workspace)
