#!/usr/bin/env sh

spacebar -m config text_font          "Helvetica Neue:Bold:13"
spacebar -m config icon_font          "Font Awesome 5 Free:Regular:12.5"
spacebar -m config background_color   0xAA000000
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config position           top
spacebar -m config height             26
spacebar -m config title              on
spacebar -m config spaces             on
spacebar -m config clock              on
spacebar -m config power              on
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config space_icon_color   0xffA6EB65
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip  "💬 Social" "🔗 Browser" "⚒️ Tools" "⌨️ Code" "💡Extra I" "💡Extra II" "💡Extra III" "💡Extra IV" "💡Extra V"
spacebar -m config power_icon_strip  🔋 🔌
spacebar -m config space_icon         
spacebar -m config clock_icon         ⏰
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%d/%m/%y %R"

echo "spacebar configuration loaded.."
