#!/bin/bash
# Scan for access points
# > sudo iw dev wlp3s0 scan | grep SSID
# create passphrase
# > wpa_passphrase "your SSID" > /etc/wpa_supplicant/yourssid.conf
# bring network up
# > sudo ip link set wlp3s0 up
# network is already exists
# > pkill wpa
# connect to wifi
# > connect-wifi yourssid
# > connect-wifi yourssid device

if [[ $2 = "" ]]; then
  dev="wlp3s0"
else
  dev=$2
fi
if [[ $1 = "" ]]; then
  network="/etc/wpa_supplicant/default.conf"
else
  network="/etc/wpa_supplicant/$1.conf"
fi

echo "Try to connect to $1 through $dev"

if [[ `iw dev $dev link` =~ "Not connect" ]]; then
  sudo wpa_supplicant -B -D wext -i $dev -c $network
fi
